In [ ]:
# 1.What is a Python library? Why do we use Python libraries

A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code for each action. These libraries typically provide pre-written code for common tasks, such as mathematical operations, data manipulation, web development, machine learning, and much more.

We use Python libraries for several reasons:

Code Reusability: Libraries encapsulate reusable code, saving developers time and effort by providing pre-built functions and classes.
Efficiency: Using libraries allows developers to leverage optimized, well-tested code rather than reinventing the wheel for every project.
Specialized Functionality: Libraries often contain specialized functionality tailored to specific tasks or domains, such as scientific computing (NumPy, SciPy), data analysis (Pandas), machine learning (scikit-learn, TensorFlow), and web development (Django, Flask).
Community Contributions: Python libraries are often open-source, meaning they are developed and maintained by a community of contributors. This collaborative effort results in robust, feature-rich libraries that evolve over time.
Interoperability: Python libraries are designed to work well together, allowing developers to combine multiple libraries to achieve complex tasks.

In [ ]:
#2.What is the difference between Numpy array and List?

In [ ]:
Array Stores homogeneous data it takess lesser time to reply
List Store Hetrogeneous type of data it takes more time than Array to reply
List is Referencing addresses.It stores the address not themselves.
Array is statically defined not dynamically like list 
Array is Fast because all data having some data types

In [4]:
# 3 . Find the shape, size and dimension of the following array?
import numpy as np

arr1 = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

In [5]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)

(3, 4)
12
2


In [9]:
#4. Write python code to access the first row of the following array?
def accessRow(arr):
    if arr.size !=0:
        print(arr[0])
accessRow(arr1)

[1 2 3 4]


In [13]:
#5.How do you access the element at the third row and fourth column from the given numpy array
print(arr1[2][3])

12


In [15]:
#6.. Write code to extract all odd-indexed elements from the given numpy array
odd_indices = arr1[:, 1::2]

print(odd_indices)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [21]:
#7.. How can you generate a random 3x3 matrix with values between 0 and 1
arr2 = np.random.rand(3, 3)

In [22]:
arr2

array([[0.69399995, 0.80115415, 0.27399678],
       [0.37775249, 0.64675373, 0.81343742],
       [0.93836154, 0.0350762 , 0.51263791]])

In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn
np.random.rand generates random numbers from a uniform distribution between 0 and 1, while np.random.randn 
generates random numbers from a standard normal distribution (mean=0, standard deviation=1).

In [25]:
#9. Write code to increase the dimension of the following array?
arr3 = np.expand_dims(arr1, axis=0)

In [26]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [28]:
#10. How to transpose the following array in NumPy
arr4 = arr1.T

In [29]:
arr4

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#11.Consider the following matrix:
 Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [34]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [35]:
#index wise multiplication
arr1*arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [37]:
#matrix multiplication
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

In [39]:
array1 @ array2

array([[19, 22],
       [43, 50]])

In [40]:
#add both matrix
arr1 + arr2 

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
#subtract matrix b from a 
arr2 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
#divide matrix b from a 
arr2/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#12.Which function in Numpy can be used to swap the byte order of an array
np.ndarray.byteswap()

In [ ]:
#13.What is the significance of the np.linalg.inv function
np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix

In [43]:
#14. What does the np.reshape function do, and how is it used
#reshape()fun is convert the original shape of array into shpae we are mention in parameter if with in range
arr1.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#What is broadcasting in Numpy?
Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined
together in arithmetic and logical operations. It enables NumPy to perform these operations even when
the shapes of the arrays are not compatible, by implicitly 
replicating the smaller array along the missing dimensions to match the shape of the larger array.